### ISSUE TITLE
rancher2_bootstrap_setup_admin fails with "error Unauthorized"

### ISSUE THREAD

**Issue by batthebee** [alexzimmer96/rancher-hcloud#14]
did all your instructions, but setup fails with following error:

```bash
│ Error: [ERROR] Login with admin user: Doing  user logging: error Unauthorized
│ 
│   with module.rancher_init.rancher2_bootstrap.setup_admin,
│   on module-rancher-init/main.tf line 80, in resource "rancher2_bootstrap" "setup_admin":
│   80: resource "rancher2_bootstrap" "setup_admin" {
│ 
```
when i login into web ui, I need to initially replace the password. I used the same one but still not possible to complete setup.

**Comment by littleBinary** [comment]
Same Error, im looking for a solution

**Comment by batthebee** [comment]
Could solve the problem. There is a brand new rancher release (3d) out there, v2.6.0 which will be used by tag latest. This release doesn't work with rancher2_bootstrap, using password. Switch to stable (version 2.5.9) worked for me. Will provide a PR next few hours/days. replace in `modules/rancher-init/main.tf` in resource `helm_release.rancher.repository` with:
```
  version = "2.5.9"
  repository = "https://releases.rancher.com/server-charts/stable"
```

did other changes, updating versions, removed most warnings, so i'm not completely sure, if change the two lines is sufficient.

**Comment by littleBinary** [comment]
I installed version 2.6.0 by hand and saw that the setup is different. The initial password must now be read out with kubectl. The passwords can then be set as normal.

 `kubectl get secret --namespace cattle-system bootstrap-secret -o go-template = '{{. data.bootstrapPassword | base64decode}} {{"\ n"}}'base64decode}} {{"\ n"}}'`

**Comment by littleBinary** [comment]
Thank you for fixing
